# Project information
site_name: iCub Firmware Models
site_url: https://robotology.github.io/icub-firmware-models
site_description: Documentation resources for the models used to generate the firmware
site_author: iCub Tech
copyright: BSD 3-Clause License

repo_name: robotology/icub-firmware-models
repo_url: https://github.com/robotology/icub-firmware-models

theme:
  name: material
  logo: assets/head-solid.png
  favicon: assets/head-solid.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tooltips
    - tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink:
      user: icub-tech-iit
      repo: documentation
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - markdown.extensions.toc:
      permalink: true

nav:
  - iCub Firmware Models:
    - Home Page: index.md
